name: Backend-Build-Deployment-$(Date:yyyyMMdd)$(Rev:.r)

pool:
  name: Self-Hosted
  demands:
    - Agent.Name -equals azure-devops-docker

trigger: none

variables:
  - name: sonar.host.url
    value: "http://sonarqube:9000"

  - name: sonar.token
    value: "sqp_5c8f222ef7f30dd0f52087e94ebcc6f4c5519007"

  - name: sonar.projectKey
    value: "todo-api-backend"

  - name: working.directory
    value: "$(System.DefaultWorkingDirectory)/backend"

resources:
  repositories:
    - repository: githubTemplate
      type: github
      endpoint: anurag-devops-principles
      name: anurag-devops-principles/devops-cicd-workflows-pipeline-library
      ref: refs/heads/main

stages:
  - template: .azure/pipeline/sonarqube.yaml@githubTemplate
    parameters:
      jobName: "Static Code Scanning"
      sonarHost: $(sonar.host.url)
      sonarToken: $(sonar.token)
      sonarProject: $(sonar.projectKey)
      workingDirectory: $(working.directory)

  - template: .azure/pipeline/todo-be-bandit.yaml@githubTemplate
    parameters:
      jobName: "Dependancy Vulnerability Security"
      workingDirectory: $(working.directory)
