name: Backend | Build | Deployment

pool: Self-Hosted

trigger: none

variables:
  - name: sonar.host.url
    value: 'http://127.0.0.1:9000'

  - name: sonar.token
    value: 'sqp_1ae1237353f184d49a087f1837045c5c0918b074'

  - name: sonar.projectKey
    value: 'todo-api-backend'

  - name: working.directory
    value: '$(System.DefaultWorkingDirectory)/backend'

resources:
  repositories:
    - respositiry: githubTemplate
      type: github
      endpoint: anurag-vj
      name: anurag-vj/devops-cicd-workflows-pipeline-library
      ref: refs/heads/main

stages:
  - template: .azure/pipeline/sonarqube.yaml@githubTemplate
    parameters:
      sonarHost: $(sonar.host.url)
      sonarToken: $(sonar.token)
      sonarProject: $(sonar.projectKey)
      workingDirectory: $(working.directory)