name: Frontend-Build-Deployment-$(Date:yyyyMMdd)$(Rev:.r)

pool:
  name: Self-Hosted
  demands:
    - Agent.Name -equals azure-devops-docker

trigger: none

variables:
  - name: sonar.host.url
    value: "http://sonarqube:9000"

  - name: sonar.token
    value: "sqp_42b126509e7fa0b59edb3bb56aca52be85cda2e4"

  - name: sonar.projectKey
    value: "todo-ui-frontend"

  - name: working.directory
    value: "$(System.DefaultWorkingDirectory)/frontend"

resources:
  repositories:
    - repository: githubTemplate
      type: github
      endpoint: anurag-devops-principles
      name: anurag-devops-principles/devops-cicd-workflows-pipeline-library
      ref: refs/heads/main

stages:
  - template: .azure/pipeline/sonarqube.yaml@githubTemplate
    parameters:
      jobName: "Static Code Scanning"
      sonarHost: $(sonar.host.url)
      sonarToken: $(sonar.token)
      sonarProject: $(sonar.projectKey)
      workingDirectory: $(working.directory)

  - template: .azure/pipeline/retirejs.yaml@githubTemplate
    parameters:
      jobName: "Dependancy Vulnerability Security"
      workingDirectory: $(working.directory)

  - template: .azure/pipeline/linting.yaml@githubTemplate
    parameters:
      jobName: "Multi Language Linting Check"
      workingDirectory: $(working.directory)

  - template: .azure/pipeline/feApplicationBuild.yaml@githubTemplate
    parameters:
      jobName: "Application Build and Package Artifacts"
      workingDirectory: $(working.directory)
