name: Frontend | Builds | Deployment

pool: Self-Hosted

trigger: none

variables:
  sonar.host.url: http://127.0.0.1:9000
  sonar.token: sqp_80a3c4ee60ab7f288e1ac246cc24a5841641b701
  sonar.projectKey: todo-ui-frontend

stages:
  - stage: StaticCodeAnalysis
    displayName: 'Static Code Analysis'
    jobs:
      - job: SonarqubeAnalysis
        displayName: 'Static Code Analysis - Sonarqube'
        steps:
          
          - task: Bash@3
            displayName: 'Sonarqube Scan'
            inputs:
              targetType: 'inline'
              script: |
                sonar-scanner \
                -D sonar.host.url=$(sonar.host.url) \
                -D sonar.token=$(sonar.token) \
                -D sonar.projectKey=$(sonar.projectKey) \
                -Dsonar.qualitygate.wait=true
            workingDirectory: '$(System.DefaultWorkingDirectory)/frontend'
